spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/tanyy777/tyy-config-demo
          default-label: main
          search-paths: config
  application:
    name: config-center

server:
  port: 8888